sudo: false
language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "7"

before_install:
  - npm install -g gulp
  - travis_retry npm install

install:
  - npm install -g codecov

script:
  - gulp build && gulp mocha
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov

matrix:
  allow_failures:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "7"
