sudo: false
language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "7"

before_install:
  - npm install -g gulp-cli
  - travis_retry npm install

install:
  - npm install -g check-node-version
  - npm install -g codecov

script:
  - bin/test-and-build.sh
  - codecov

matrix:
  allow_failures:
    - node_js: "0.10"
    - node_js: "0.12"
