sudo: false
language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "7"

before_install:
  - npm install -g gulp
  - travis_retry npm install

script:
  - gulp test

matrix:
  allow_failures:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "7"
